### ISSUE TITLE
"Simplest Possible App" fails with "No such module"

### ISSUE THREAD

**Issue by Bjoern** [kanso/kanso#408]
I just tried kanso and went through the "Getting Started" Tutorial.

I have created index.html and kanso.json as described in the docs for "Simplest Possible App". Now if I type kanso install I get

Error: Error: No such module
    at Object.<anonymous> (/usr/local/lib/node_modules/kanso/lib/utils.js:14:21)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/kanso/bin/kanso:4:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
Failed

This is the first time I tried kanso so I have no idea what is wrong.

I'm on OS X, nodejs version is v0.11.11 with --harmony flag

**Comment by flimzy** [comment]
I'm having the same problem. Any update on this?
