### ISSUE TITLE
process.binding('evals') is deprecated, breaks on node 0.12.0

### ISSUE THREAD

**Issue by toomasp** [kanso/kanso#422]
From: http://nodejs.org/changelog.html

# 2010.11.16 Version 0.3.1 (unstable), ce9a54
__API: Move process.binding('evals') to require('vm')__

Actions fail with:

```
Error: Error: No such module: evals
    at Error (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/kanso/lib/utils.js:14:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/kanso/bin/kanso:4:13)
    at Module._compile (module.js:460:26)
Failed
```

**Comment by garethbowen** [comment]
PR merged - we'll release 0.4.2 soon. Thanks!

**Comment by alxndrsn** [comment]
Hi gareth, this is still happening for me - node 0.12.2 and kanso 0.5.0

**Comment by natevw** [comment]
I'm getting this too, in my case the stack trace looks like:

```
$ kanso push backend
Reading dependency tree...
loading backend
Error: Error: No such module: evals
    at Error (native)
    at Object.<anonymous> (/Users/natevw/…/myproject/backend/packages/traditional-couchapp/node_modules/kanso-utils/utils.js:12:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/natevw/…/myproject/backend/packages/traditional-couchapp/build/utils.js:3:13)
    at Module._compile (module.js:460:26)
Failed
```

So in my case, it is due to https://github.com/kanso/traditional-couchapp/issues/3 — the traditional-couchapp plugin (and perhaps some others) still publishes its own copy of node_modules and didn't get updated.

My workaround, since I'd already checked in the kanso dependencies when the future of kanso's package repository was in doubt, was to just manually edit that file ("packages/traditional-couchapp/build/utils.js" in the kanso project folder) and changed `process.binding('evals')` to `require('vm')` as done in e.g. https://github.com/kanso/kanso/commit/5c9bf0923f7e364560e644b851ff09e922900abc
